
# remote_theme: pages-themes/hacker@v0.2.0

# emote_theme: pages-themes/minimal@v0.2.0

# remote_theme: pages-themes/midnight@v0.2.0

# remote_theme: pages-themes/slate@v0.2.0

# remote_theme: pages-themes/modernist@v0.2.0

# remote_theme: pages-themes/dinky@v0.2.0

# remote_theme: pages-themes/leap-day@v0.2.0

# remote_theme: pages-themes/merlot@v0.2.0

# remote_theme: pages-themes/tactile@v0.2.0

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [EndeavourOS Beginner's Basics]
tagline: [A beginner-to-intermediate user's guide to system maintenance in EndeavourOS.]
description: [This beginner-to-intermediate user's guide covers the basics of maintaining your Endeavour OS system by using terminal commands in the command-line interface (CLI).]